repos:
-   repo: local
    hooks:
      - id: lint
        name: Lint
        entry: make lint
        language: system
      - id: format
        name: Format
        entry: make format
        language: system